# Generated by Django 5.1.7 on 2025-06-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_metatest_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatest',
            name='updated',
            field=models.DateTimeField(
                auto_now=True, help_text='Timestamp of the connection creation.'
            ),
        ),
    ]
